name:                adventofcode2024
version:             0.20.2.0
github:              "cronokun/advent-of-code-2024"
license:             BSD-3-Clause
author:              "Crono"
maintainer:          "crono.neko@gmail.com"
copyright:           "2025 Crono"

extra-source-files:
- README.md

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         "Solutions for Advent of Code 2024."

dependencies:
- base >= 4.7 && < 5
- containers >= 0.7
- heaps >= 0.4

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-language: GHC2024

library:
  source-dirs: src

tests:
  adventofcode2024-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventofcode2024
    - HUnit >= 1.6
    - hspec >= 2.11
